/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    DemoBox: typeof import('./src/components/DemoBox.vue')['default']
    DemoContainer: typeof import('./src/components/demoContainer.vue')['default']
    JAdvancedSearch: typeof import('jetlinks-ui-components/es')['AdvancedSearch']
    JButton: typeof import('jetlinks-ui-components/es')['Button']
    JInput: typeof import('jetlinks-ui-components/es')['Input']
    JRadioButton: typeof import('jetlinks-ui-components/es')['RadioButton']
    JRadioGroup: typeof import('jetlinks-ui-components/es')['RadioGroup']
    JSearch: typeof import('jetlinks-ui-components/es')['Search']
    RiceCarbonAds: typeof import('./src/components/rice/CarbonAds.vue')['default']
    RiceGeektime: typeof import('./src/components/rice/geektime.vue')['default']
    RiceGeektime_ads: typeof import('./src/components/rice/geektime_ads.vue')['default']
    RiceGoogleAds: typeof import('./src/components/rice/GoogleAds.vue')['default']
    RiceGoogleAdsMin: typeof import('./src/components/rice/GoogleAdsMin.vue')['default']
    RiceGoogleAdsTop: typeof import('./src/components/rice/GoogleAdsTop.vue')['default']
    RiceRight_bottom_rice: typeof import('./src/components/rice/right_bottom_rice.vue')['default']
    RiceSponsors: typeof import('./src/components/rice/sponsors.vue')['default']
    RiceTop_rice: typeof import('./src/components/rice/top_rice.vue')['default']
    RiceWWAds: typeof import('./src/components/rice/WWAds.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleLayout: typeof import('./src/components/SimpleLayout.vue')['default']
    SurelyVue: typeof import('./src/components/surelyVue.vue')['default']
  }
}
